### ISSUE TITLE
Using Github for Requirements Tracking

### ISSUE THREAD

**Issue by bennettmorrison** [bennettmorrison/Test#1]
As a Product Manger who is writing requirements for Features, I want a tool that can capture requirements and acceptance criteria, and can coordinate workflow for developers and QA so that all parties are on the same page when it comes to creating features.

Acceptance Criteria-
- [x] Ability to capture requirements 
- [x] Ability to assign requirements
- [x] Ability to break requirements into sub-tasks
- [x] Ability to house UI mockups
- [x] Ability to capture discussion about issues
- [x] Ability to be used for Bugs
- [x] Ability to be used for Front-End and Back-End developers to coordinate work

**Comment by bennettmorrison** [comment]
Assignee allows someone to be assigned.
Requirements can be captured in the issue.
Subtasks can be added in the markdown (see the checkboxes above), but it would be better to refer to issues by adding the name of the repo and issue number. This would link them. Like bennettmorrison/Test#2

**Comment by bennettmorrison** [comment]
You can add UX pretty simply by adding images

![screenshot 2013-12-12 10 40 55](https://cloud.githubusercontent.com/assets/3522703/7377359/e5ff1bb8-edb3-11e4-9448-0aa6ea5590e8.png)

**Comment by bennettmorrison** [comment]
**References** should be used to coordinate work--especially between back-end and front-end code.

See note discussion: https://guides.github.com/features/issues/#notifications

**BUT** references don't show up in Waffle.io. Just the links.

**Comment by bennettmorrison** [comment]
**Milestones** can be used to coordinate releases. (This is already how it is being used--using Semantic Versioning -- http://semver.org/.)
**Labels** can be used to designate feature work (vs. bugs/defects), feature groups, and teams. (I think Roman already started working on this.)

**Comment by bennettmorrison** [comment]
**Limitations**
- Business-level backlog (would need someway to coordinate--like JIRA to Confluence. Maybe through Labels and Milestones
- Is only at the repo level, and you can't copy an issue from repo to repo. (We'd need to fork something like https://github.com/google/github-issue-mover)
